//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wappm_limena.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BI_Accounts_receivable
    {
        public Nullable<System.DateTime> Date { get; set; }
        public int DocNum { get; set; }
        public string Type { get; set; }
        public string CardCode { get; set; }
        public string CardName { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Zone { get; set; }
        public int SalesRepCode { get; set; }
        public string SalesRep { get; set; }
        public string PaymentTerm { get; set; }
        public string Aging { get; set; }
        public Nullable<int> idAging { get; set; }
    }
}
