//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wappm_limena.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BI_Email_RA_Head
    {
        public long ID_generico { get; set; }
        public Nullable<int> SlpCode { get; set; }
        public string Descr { get; set; }
        public decimal Budget { get; set; }
        public decimal Returns { get; set; }
        public Nullable<decimal> Achv { get; set; }
    }
}
