//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wappm_limena.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BI_Email_RA
    {
        public System.DateTime Date { get; set; }
        public string DayWeek { get; set; }
        public string id_Customer { get; set; }
        public string CardName { get; set; }
        public string ItemName { get; set; }
        public int id_SalesRep { get; set; }
        public long ID_generico { get; set; }
        public decimal Returns { get; set; }
        public decimal Budget { get; set; }
        public string Reason { get; set; }
    }
}
