//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wappm_limena.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DLI_PROEntities : DbContext
    {
        public DLI_PROEntities()
            : base("name=DLI_PROEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BI_Email_RA> BI_Email_RA { get; set; }
        public virtual DbSet<BI_Email_RA_Head> BI_Email_RA_Head { get; set; }
        public virtual DbSet<BI_Accounts_receivable> BI_Accounts_receivable { get; set; }
        public virtual DbSet<BI_Sales_Report> BI_Sales_Report { get; set; }
        public virtual DbSet<view_VendorsData> view_VendorsData { get; set; }
    }
}
