//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wappm_limena.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_FACTORS
    {
        public string SubCategory { get; set; }
        public string Brand { get; set; }
        public string Vendor { get; set; }
        public string ItemCode { get; set; }
        public string ItemName { get; set; }
        public string Active { get; set; }
        public string Pepperi { get; set; }
        public string BuyUoM { get; set; }
        public decimal BuyFactor { get; set; }
        public string UoMGroup { get; set; }
        public decimal COST { get; set; }
        public decimal SRP { get; set; }
        public decimal MAIN_LIST_Price { get; set; }
        public decimal MAIN_LIST_Factor { get; set; }
        public decimal DIAMOND_Price { get; set; }
        public decimal DIAMOND_Factor { get; set; }
        public decimal GOLD_Price { get; set; }
        public decimal GOLD_Factor { get; set; }
        public decimal SILVER_Price { get; set; }
        public decimal SILVER_Factor { get; set; }
    }
}
