//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wappm_limena.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_ItemList
    {
        public string ItemCode { get; set; }
        public string ItemName { get; set; }
        public string Buy_Unit { get; set; }
        public decimal Buy_Qty { get; set; }
        public decimal ListPrice { get; set; }
        public decimal SRP { get; set; }
        public decimal ItemCost { get; set; }
        public decimal Margin { get; set; }
        public decimal StockUnits { get; set; }
        public decimal StockCases { get; set; }
        public decimal TotalInventoryCost { get; set; }
        public string Brand { get; set; }
        public string Category { get; set; }
        public string SubCategory { get; set; }
        public string Vendor_ItemCode { get; set; }
        public string UPC { get; set; }
        public string UoM_Group { get; set; }
        public string VendorCode { get; set; }
        public string Vendor { get; set; }
        public string Active { get; set; }
        public string Pepperi { get; set; }
        public string U_Return { get; set; }
        public decimal U_Ti { get; set; }
        public decimal U_HI { get; set; }
        public decimal U_PalletCount { get; set; }
        public string U_BinLocation { get; set; }
        public string StorageType { get; set; }
        public string SWW { get; set; }
        public string PicturName { get; set; }
        public string ItemClasif { get; set; }
        public decimal ItemComission { get; set; }
        public decimal Weight__Lbs_ { get; set; }
        public System.DateTime CreationDate { get; set; }
        public short U_PorcMin { get; set; }
    }
}
