//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wappm_limena.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_VendorsData
    {
        public int No_FACTURA { get; set; }
        public System.DateTime FECHA_FACTURA { get; set; }
        public short MES_FACTURA { get; set; }
        public short ANO_FACTURA { get; set; }
        public string NOMBRE_CLIENTE { get; set; }
        public string PAIS { get; set; }
        public string STATE { get; set; }
        public string CODIGO_ARTICULO { get; set; }
        public string DESCRIPCION_ARTICULO { get; set; }
        public string FAMILIA { get; set; }
        public string CANAL { get; set; }
        public string MARCA { get; set; }
        public string VENDEDOR { get; set; }
        public decimal CANTIDAD_EN_CAJAS { get; set; }
        public decimal VALOR_DE_VENTA_EN_US { get; set; }
        public decimal COSTO_TOTAL_EN_US { get; set; }
        public string CODIGO_CLIENTE { get; set; }
        public long ID_generico { get; set; }
    }
}
